# Generated by Django 4.1 on 2022-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="customuser",
            name="birthDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
