# Generated by Django 4.1 on 2022-12-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_customuser_address_customuser_birthdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="description",),
        migrations.RemoveField(model_name="customuser", name="status",),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
