# Generated by Django 4.1 on 2022-12-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("createdOn", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("si", "Still Image"),
                            ("ai", "Animated Image"),
                            ("cv", "Customized Video"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.FloatField()),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateTimeField(auto_now_add=True)),
                ("orderDate", models.DateTimeField()),
                (
                    "paymentType",
                    models.CharField(
                        choices=[("cc", "Credit Card"), ("dc", "Debit Card")],
                        max_length=2,
                    ),
                ),
                ("cardNum", models.IntegerField()),
                ("cardExp", models.DateField()),
                ("comments", models.TextField()),
                ("ordererd", models.CharField(default="false", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MoMaShop.item"
                    ),
                ),
            ],
        ),
    ]
