# Generated by Django 4.1 on 2022-12-20 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SI", "Still Image"),
                            ("AI", "Animated Image"),
                            ("CV", "Customized Video"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.FloatField()),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MoMaShop.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateTimeField(auto_now_add=True)),
                ("orderDate", models.DateTimeField()),
                (
                    "paymentType",
                    models.CharField(
                        choices=[("CC", "Credit Card"), ("DC", "Debit Card")],
                        max_length=2,
                    ),
                ),
                ("cardNum", models.IntegerField()),
                ("cardExp", models.DateField()),
                ("comments", models.TextField()),
                ("ordererd", models.BooleanField(default=False)),
                ("items", models.ManyToManyField(to="MoMaShop.orderitem")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
