# Generated by Django 4.1 on 2022-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MoMaShop", "0004_alter_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="MoMaShop.orderitem"),
        ),
    ]
